---
abstract: 'Read JSON into a Perl variable'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Parse
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008009'
resources:
  bugtracker: https://github.com/benkasminbullock/JSON-Parse/issues
  repository: git://github.com/benkasminbullock/JSON-Parse.git
version: '0.40'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
